# Generated by Django 2.1.7 on 2019-03-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_category_hall_seat_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movie_category', to='webapp.Category'),
        ),
    ]
