# Generated by Django 2.1.7 on 2019-03-04 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='show_hall', to='webapp.Hall'),
        ),
    ]
