# Generated by Django 2.1.7 on 2019-03-07 06:43

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20190307_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=webapp.models.generate_code, editable=False, max_length=10, unique_for_date='created_at'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
